
import React from 'react';
import { 
  Wrench, 
  Zap, 
  Trash2, 
  Hammer, 
  Car, 
  Paintbrush, 
  Wind, 
  Scissors 
} from 'lucide-react';
import { Category, ServiceProvider } from './types';

export const CATEGORIES: Category[] = [
  { id: 'plumbing', name: 'Plumbing', icon: 'wrench', color: 'bg-blue-100 text-blue-600' },
  { id: 'electrical', name: 'Electrical', icon: 'zap', color: 'bg-yellow-100 text-yellow-600' },
  { id: 'cleaning', name: 'Cleaning', icon: 'trash-2', color: 'bg-green-100 text-green-600' },
  { id: 'carpentry', name: 'Carpentry', icon: 'hammer', color: 'bg-orange-100 text-orange-600' },
  { id: 'mechanic', name: 'Mechanic', icon: 'car', color: 'bg-red-100 text-red-600' },
  { id: 'painting', name: 'Painting', icon: 'paintbrush', color: 'bg-purple-100 text-purple-600' },
  { id: 'hvac', name: 'AC Repair', icon: 'wind', color: 'bg-cyan-100 text-cyan-600' },
  { id: 'beauty', name: 'Saloon', icon: 'scissors', color: 'bg-pink-100 text-pink-600' },
];

export const MOCK_PROVIDERS: ServiceProvider[] = [
  {
    id: 'p1',
    name: 'Samuel Okoth',
    phone: '+254712345678',
    role: 'provider',
    avatar: 'https://picsum.photos/seed/p1/200/200',
    category: 'plumbing',
    rating: 4.8,
    reviewCount: 124,
    pricePerHour: 1500,
    bio: 'Professional plumber with over 10 years experience in modern home piping and repairs.',
    skills: ['Pipe Fitting', 'Clogged Drains', 'Solar Heater Repair'],
    isVerified: true,
    distance: 1.2,
    availability: 'online',
  },
  {
    id: 'p2',
    name: 'Jane Wambui',
    phone: '+254722334455',
    role: 'provider',
    avatar: 'https://picsum.photos/seed/p2/200/200',
    category: 'electrical',
    rating: 4.9,
    reviewCount: 89,
    pricePerHour: 2000,
    bio: 'Certified electrician specializing in smart home installation and wiring.',
    skills: ['Circuit Repair', 'Light Installation', 'Industrial Wiring'],
    isVerified: true,
    distance: 0.8,
    availability: 'online',
  },
  {
    id: 'p3',
    name: 'Michael Kibet',
    phone: '+254733445566',
    role: 'provider',
    avatar: 'https://picsum.photos/seed/p3/200/200',
    category: 'mechanic',
    rating: 4.5,
    reviewCount: 56,
    pricePerHour: 1200,
    bio: 'Automotive expert for all major vehicle models. Mobile repair available.',
    skills: ['Engine Diagnostic', 'Brake Service', 'Oil Change'],
    isVerified: false,
    distance: 2.5,
    availability: 'online',
  },
  {
    id: 'p4',
    name: 'Sarah Mwangi',
    phone: '+254744556677',
    role: 'provider',
    avatar: 'https://picsum.photos/seed/p4/200/200',
    category: 'cleaning',
    rating: 4.7,
    reviewCount: 210,
    pricePerHour: 800,
    bio: 'Deep cleaning services for homes and offices. We use eco-friendly products.',
    skills: ['Carpet Cleaning', 'Post-Construction Cleaning', 'Laundry'],
    isVerified: true,
    distance: 1.5,
    availability: 'offline',
  },
];
